---
- name: Install apt-transport-https and gpg
  apt:
    name:
      - apt-transport-https
      - gnupg2  # required for Ansible's apt_key module
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Checking to see if the Jellyfin PGP key is already present
  ansible.builtin.stat:
    path: /usr/share/keyrings/jellyfin.gpg.asc
  register: keyring

- name: Download Jellyfin Team GPG key
  ansible.builtin.get_url:
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
    checksum: sha256:a0cde241ae297fa6f0265c0bf15ce9eb9ee97c008904a59ab367a67d59532839
    dest: /usr/share/keyrings/jellyfin.gpg.asc
    mode: '644'
  when: "'stat' in keyring and not keyring.stat.exists"

- name: Add Jellyfin repository
  apt_repository:
    repo: >
      deb [signed-by=/usr/share/keyrings/jellyfin.gpg.asc] https://repo.jellyfin.org/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    state: present

- name: Install Jellyfin and {{ jellyfin_HTTP_server }}
  apt:
    update_cache: true
    name:
      - jellyfin
      - "{{ jellyfin_HTTP_server }}"
      # required for Ansible's xml module
      - python{{ "3" if ansible_python.version.major == 3 }}-lxml
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Enable Jellyfin and {{ jellyfin_HTTP_server }}
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - jellyfin
    - "{{ jellyfin_HTTP_server }}"
...
